In [1]:
# Reference site: https://pypi.org/project/instagramy/#Instagram-User-details

In [2]:
# pip install instagramy

In [3]:
# pip install instagramy --upgrade

In [4]:
from instagramy import InstagramUser
from instagramy import InstagramPost
import pandas as pd

In [5]:
# Grab session id: 
# log into Instagram in browser, 
    # inspect page --> 
    # click on application tab --> 
    # expand cookies (left hand side under 'Storage') --> 
    # click on cookie for https://instagram.com --> 
    # copy session id from the table
    
session_id = "49271793291%3Afm32SvJNf04n27%3A10"

In [6]:
# Separately, we created a list of Instagram users from whom we want to pull data
# Import list of users

# Read in separate list of pre-selected usernames into pandas dataframe
user_df = pd.read_csv('resources/top_ig_urls_MJ.csv', header=None)

# Show usernames
user_df

                      0
0              shmee150
1         diwd_official
2        thatdudeinblue
3        thesmokingtire
4            hudabeauty
5          jamescharles
6          rclbeauty101
7          glamlifeguru
8            Jaclynhill
9               garyvee
10         grantcardone
11      thesharkdaymond
12       chiaraferragni
13        oliviapalermo
14        marianodivaio
15  teachingmensfashion
16              evelina
17          jamieoliver
18       rosannapansino
19    bingingwithbabish
20          junskitchen
21                Ninja
22           markiplier
23         SSSniperWolf
24         unboxtherapy
25                MKBHD
26        kayla_itsines
27       michelle_lewin
28          simeonpanda
29           blogilates
30          whatsupmoms
31        amberfillerup
32            glowmaven
33     realmomnutrition
34        techsavvymama
35          funforlouis
36         chrisburkard
37         wil_dasovich
38  thebucketlistfamily
39                izkiz
40         thrivewithco

In [8]:
# Create function to scrape Instagram user details into lists that we can later put into dataframe

# Creat empty lists
user_followers = []
user_posts = []
user_following = []
user_bio = []

# Create function to loop over Instagram users and append scraped info to lists above
def scrape_detail():
    for x in user_df[0]:
        try:
                  
            # Connect to profile
            user = InstagramUser( x, sessionid=session_id)

            # Scrape specific info
            user_followers.append( user.number_of_followers)
            user_posts.append( user.number_of_posts)
            user_following.append( user.number_of_followings)
            user_bio.append( user.biography)
        
        except:
            user_followers.append( "error")
            user_posts.append( "error")
            user_following.append( "error")
            user_bio.append( "error")

# Run function
scrape_detail()

In [9]:
# Create dataframe for holding the information we scraped
user_list_df = pd.DataFrame( columns= ['account', 'bio','followers', 'following' 'posts'])

In [10]:
# Add scraped info into the dataframe
user_list_df.account = user_df[0]
user_list_df.bio = user_bio
user_list_df.followers = user_followers
user_list_df.following = user_following
user_list_df.posts = user_posts

# Show dataframe
user_list_df

C:\Users\mjensen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """
C:\Users\mjensen\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

                account    bio followers followingposts
0              shmee150  error     error            NaN
1         diwd_official  error     error            NaN
2        thatdudeinblue  error     error            NaN
3        thesmokingtire  error     error            NaN
4            hudabeauty  error     error            NaN
5          jamescharles  error     error            NaN
6          rclbeauty101  error     error            NaN
7          glamlifeguru  error     error            NaN
8            Jaclynhill  error     error            NaN
9               garyvee  error     error            NaN
10         grantcardone  error     error            NaN
11      thesharkdaymond  error     error            NaN
12       chiaraferragni  error     error            NaN
13        oliviapalermo  error     error            NaN
14        marianodivaio  error     error            NaN
15  teachingmensfashion  error     error            NaN
16              evelina  error     error            NaN
17          jamieoliver  error     error            NaN
18       rosannapansino  error     error            NaN
19    bingingwithbabish  error     error            NaN
20          junskitchen  error     error            NaN
21                Ninja  error     error            NaN
22           markiplier  error     error            NaN
23         SSSniperWolf  error     error            NaN
24         unboxtherapy  error     error            NaN
25                MKBHD  error     error            NaN
26        kayla_itsines  error     error            NaN
27       michelle_lewin  error     error            NaN
28          simeonpanda  error     error            NaN
29           blogilates  error     error            NaN
30          whatsupmoms  error     error            NaN
31        amberfillerup  error     error            NaN
32            glowmaven  error     error            NaN
33     realmomnutrition  error     error            NaN
34        techsavvymama  error     error            NaN
35          funforlouis  error     error            NaN
36         chrisburkard  error     error            NaN
37         wil_dasovich  error     error            NaN
38  thebucketlistfamily  error     error            NaN
39                izkiz  error     error            NaN
40         thrivewithco  error     error            NaN

In [ ]:
post_shortcode = []
user = InstagramUser('shmee150', sessionid=session_id)
post = user.posts[0]

In [ ]:
post.shortcode

In [ ]:
for post in user.posts:
    post_shortcode.append(post.shortcode)
    
print( post_shortcode)

In [ ]:
post = InstagramPost('CSzoxcyrzj2', sessionid=session_id)
post.text